// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rygeuknbwzehplehugcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5Z2V1a25id3plaHBsZWh1Z2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxOTA0MDYsImV4cCI6MjA3OTc2NjQwNn0.bqIpZNHJRxponqJ9kSQUSJplCol3dhvBRcUN928sh1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);